// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// vz_kbd //
// ------ //

#define vz_kbd_wrap_target 0
#define vz_kbd_wrap 7

static const uint16_t vz_kbd_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6006, //  1: out    pins, 6                    
    0x202e, //  2: wait   0 pin, 14                  
    0x4008, //  3: in     pins, 8                    
    0x80a0, //  4: pull   block                      
    0x6006, //  5: out    pins, 6                    
    0x20ae, //  6: wait   1 pin, 14                  
    0x0002, //  7: jmp    2                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program vz_kbd_program = {
    .instructions = vz_kbd_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config vz_kbd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vz_kbd_wrap_target, offset + vz_kbd_wrap);
    return c;
}
#endif
